server:
  port: 8189
  servlet:
    context-path: /springbootsimple
spring:
  datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/springboot_simple?createDatabaseIfNotExist=true #&amp;allowPublicKeyRetrieval=true&amp;useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;serverTimezone=UTC
        username: root
        password: eseveb12
  jpa:
    show-sql: true
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false